; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=sparcv9 | FileCheck --check-prefix=SPARC %s
; RUN: llc < %s -mtriple=sparcv9 -mattr=+vis,+fast-fsrc2 | FileCheck --check-prefix=SPARC-FSRC2 %s

;; Early SPARC processors prefer FMOV to do FP register copies.
;; T4 and newer ones prefer FSRC2 to do FP register copies.

define float @fmovs(float %a, float %b) nounwind {
; SPARC-LABEL: fmovs:
; SPARC:       ! %bb.0: ! %entry
; SPARC-NEXT:    fmovs %f3, %f0
; SPARC-NEXT:    retl
; SPARC-NEXT:    nop
;
; SPARC-FSRC2-LABEL: fmovs:
; SPARC-FSRC2:       ! %bb.0: ! %entry
; SPARC-FSRC2-NEXT:    fsrc2s %f3, %f0
; SPARC-FSRC2-NEXT:    retl
; SPARC-FSRC2-NEXT:    nop
entry:
  ret float %b
}

define double @fmovd(double %a, double %b) nounwind {
; SPARC-LABEL: fmovd:
; SPARC:       ! %bb.0: ! %entry
; SPARC-NEXT:    fmovd %f2, %f0
; SPARC-NEXT:    retl
; SPARC-NEXT:    nop
;
; SPARC-FSRC2-LABEL: fmovd:
; SPARC-FSRC2:       ! %bb.0: ! %entry
; SPARC-FSRC2-NEXT:    fsrc2 %f2, %f0
; SPARC-FSRC2-NEXT:    retl
; SPARC-FSRC2-NEXT:    nop
entry:
  ret double %b
}
